# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.provider "virtualbox" do |v|
	  v.memory = 8000
	  v.cpus = 2
	  v.name = "nginx"
	end

  #config.vm.host_name = "nginx.stevehome.online"
  
  config.vm.box = "bento/ubuntu-16.04"
  
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 4444
   
  config.vm.provision "file", source: "setupPackage.rar", destination: "~/setupPackage.rar"
  
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y
	 
    apt-get install nginx-full unrar -y  
	
	rm -rf /etc/nginx/sites-available/default
	
	mkdir /etc/nginx/ssl/
	unrar x setupPackage.rar
	cp *.pem /etc/nginx/ssl/
	cp stevehome.online /etc/nginx/sites-available/
	ln -s /etc/nginx/sites-available/stevehome.online /etc/nginx/sites-enabled/stevehome.online
	openssl dhparam -out /etc/nginx/dhparam.pem 2048
	
	nginx -t
    service nginx restart
	echo "nginx service restarted"
	
	apt-get autoremove
  SHELL
    
  config.vm.post_up_message = <<-MESSAGE
		   
         _nnnn_
        dGGGGMMb
       @p~qp~~qMb
       M|@||@) M|        Base box bento/ubuntu-16.04
       @,----.JM|        SSH 2222 (guest)
      JS^\__/  qKL       HTTP 80 (guest) => 8080 (host)
     dZP        qKRb     HTTPS 443 (guest) => 4444 (host)
    dZP          qKKb    Log location /var/logs/nginx
   fZP            SMMb   Cert location /etc/nginx/ssl/
   HZM            MMMM   Version 0.0.1b
   FqM            MMMM   Keywords nginx unrar ssl certificate tls ubuntu
 __| ".        |\dS"qML  
 |    `.       | `' \Zq
_)      \.___.,|     .'
\____   )MMMMMP|   .'
     `-'       `--'
  
  MESSAGE
  
end
