# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.provider "virtualbox" do |v|
	  v.memory = 8000
	  v.cpus = 2
	  v.name = "nginx"
	end

  config.vm.host_name = "nginx.stevehome.online"
  
  config.vm.box = "bento/ubuntu-16.04"
  
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 4444
   
  config.vm.provision "file", source: "setupPackage.rar", destination: "~/setupPackage.rar"
  
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get upgrade -y
	 
    apt-get install nginx-full unrar -y  
	nginx -t
    service nginx restart
	
	mkdir /etc/nginx/ssl/
	
	#cp *.pem /etc/nginx/ssl/
	#ln -s /etc/nginx/sites-available/stevehome.online /etc/nginx/sites-enabled/stevehome.online
	#rm /etc/nginx/sites-enabled/default
		
	nginx -t
    service nginx restart
	
	apt-get autoremove
  SHELL
  
  #config.ssh.username = 'root'
  #config.ssh.password = 'ProxyAdmin2018'
  #config.ssh.insert_key = 'true'
  
  config.vm.post_up_message = <<-MESSAGE
          _______  
         /       /
___     /   ____/   
\   \  /   /\       SSH 2222 (guest)
 \   \/___/  \      HTTP 80 (guest) => 8080 (host)
  \       \   \     HTTPS 443 (guest) => 4444 (host)
   \_______\   \    Cert location /etc/nginx/ssl/
           /   /    Version 0.0.1b    
          /   /     Keywords nginx unrar ssl certificate tls
          \  /        
           \/
  
  MESSAGE
  
end
